# Change these first
owner: CN-Vito # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: CN
    url: https://cosanostra.pw
  - name: CN - IRC
    check: "tcp-ping"
    url: 15.204.175.58
    port: 6667

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: Service Status
  introMessage: 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
